version: "3.8"

services:
    sftp:
        image: atmoz/sftp
        ports:
            - "9922:22"
        env_file:
            - .env
        networks:
          - turreta_network

networks:
  turreta_network:
    driver: bridge